// Measurement only: never serialized into causal state or used by a law.
export interface Counters {
  reviewWakesRequested: number;
  reviewWakesExecuted: number;
  reviewWakesCoalesced: number;
  wakeSameStateDrops: number;
  wakeCapDeferrals: number;
  periodicWakes: number;
  thresholdWakes: number;
  completionWakes: number;
  failureWakes: number;
  reviewEuTotal: number;
  trialEu: number;
  informationEu: number;
  trialCandidates: number;
  inquiryClasses: number;
  descriptorEu: number;
  retrievalEu: number;
  bindingEu: number;
  forecastEu: number;
  routeEu: number;
  agendaAdmitted: number;
  agendaDeferred: number;
  drivesConsidered: number;
  bindingNodes: number;
  methodsConsidered: number;
  targetsVisited: number;
  forecastOptions: number;
  forecastBlocks: number;
  feasibilityRejected: number;
  severeRiskRejected: number;
  incumbentRetained: number;
  alternativeSelected: number;
  autonomousIntentionsCommitted: number;

  workSettlements: number;
  extractionBoundaries: number;
  conditionSegments: number;
  fatigueClosures: number;
  enjoymentClosures: number;
  bodyMaterialisations: number;
  bodyCommits: number;
  resourceMaterialisations: number;
  workGoodsTransactions: number;
  workSegmentsStarted: number;
  consumptionSettlements: number;
  learningSettlements: number;
  representativeBodyClosures: number;
  bodyEvidenceDeliveries: number;
  methodRecordsConsulted: number;
  recoverPaidSegments: number;

  currentTaskLookups: number;
  terminalTaskRowsVisited: number;
  activeTaskRowsVisited: number;
  paidPrefixRowsVisited: number;
  personalReadEntriesVisited: number;
  personalReadPagesVisited: number;
  personalGeographyCopied: number;
  personalRegionRecordsConsulted: number;
  personalRouteHeapPushes: number;
  personalRouteHeapPops: number;
  personalRouteHeapRebuilds: number;
  personalRouteHostResumes: number;
  personalRouteCellsConsulted: number;
  reservationRecordsVisited: number;
  contentEntriesVisited: number;
  geographyRegionBuildCells: number;

  perceptionCandidateChecks: number;
  routineObservations: number;
  evidenceUpdates: number;
  personalMapUpdates: number;
  memoryEvictions: number;
  personalRouteRegionExpansions: number;
  personalRouteSearches: number;
  personalRouteExpansions: number;
  runtimeStepStarts: number;
  runtimeStepCompletions: number;
  continueTransitions: number;
  repairRequiredTransitions: number;
  taskInterruptions: number;
  personalViewProjections: number;
  autonomousDeliberations: number;
  events: number;
  staleEvents: number;
  heapPushes: number;
  heapPops: number;
  heapCompactions: number;
  transactionCommits: number;
  transactionRejections: number;
  routeSearches: number;
  routeExpansions: number;
  routeRegionExpansions: number;
  spatialQueries: number;
  projectionEntities: number;
  checkpoints: number;
  checkpointBytes: number;
}
export function counters(): Counters {
  return {
    reviewWakesRequested: 0,
    reviewWakesExecuted: 0,
    reviewWakesCoalesced: 0,
    wakeSameStateDrops: 0,
    wakeCapDeferrals: 0,
    periodicWakes: 0,
    thresholdWakes: 0,
    completionWakes: 0,
    failureWakes: 0,
    reviewEuTotal: 0,
    trialEu: 0,
    informationEu: 0,
    trialCandidates: 0,
    inquiryClasses: 0,
    descriptorEu: 0,
    retrievalEu: 0,
    bindingEu: 0,
    forecastEu: 0,
    routeEu: 0,
    agendaAdmitted: 0,
    agendaDeferred: 0,
    drivesConsidered: 0,
    bindingNodes: 0,
    methodsConsidered: 0,
    targetsVisited: 0,
    forecastOptions: 0,
    forecastBlocks: 0,
    feasibilityRejected: 0,
    severeRiskRejected: 0,
    incumbentRetained: 0,
    alternativeSelected: 0,
    autonomousIntentionsCommitted: 0,

    workSettlements: 0,
    extractionBoundaries: 0,
    conditionSegments: 0,
    fatigueClosures: 0,
    enjoymentClosures: 0,
    bodyMaterialisations: 0,
    bodyCommits: 0,
    resourceMaterialisations: 0,
    workGoodsTransactions: 0,
    workSegmentsStarted: 0,
    consumptionSettlements: 0,
    learningSettlements: 0,
    representativeBodyClosures: 0,
    bodyEvidenceDeliveries: 0,
    methodRecordsConsulted: 0,
    recoverPaidSegments: 0,

    currentTaskLookups: 0,
    terminalTaskRowsVisited: 0,
    activeTaskRowsVisited: 0,
    paidPrefixRowsVisited: 0,
    personalReadEntriesVisited: 0,
    personalReadPagesVisited: 0,
    personalGeographyCopied: 0,
    personalRegionRecordsConsulted: 0,
    personalRouteHeapPushes: 0,
    personalRouteHeapPops: 0,
    personalRouteHeapRebuilds: 0,
    personalRouteHostResumes: 0,
    personalRouteCellsConsulted: 0,
    reservationRecordsVisited: 0,
    contentEntriesVisited: 0,
    geographyRegionBuildCells: 0,

    perceptionCandidateChecks: 0,
    routineObservations: 0,
    evidenceUpdates: 0,
    personalMapUpdates: 0,
    memoryEvictions: 0,
    personalRouteRegionExpansions: 0,
    personalRouteSearches: 0,
    personalRouteExpansions: 0,
    runtimeStepStarts: 0,
    runtimeStepCompletions: 0,
    continueTransitions: 0,
    repairRequiredTransitions: 0,
    taskInterruptions: 0,
    personalViewProjections: 0,
    autonomousDeliberations: 0,
    events: 0,
    staleEvents: 0,
    heapPushes: 0,
    heapPops: 0,
    heapCompactions: 0,
    transactionCommits: 0,
    transactionRejections: 0,
    routeSearches: 0,
    routeExpansions: 0,
    routeRegionExpansions: 0,
    spatialQueries: 0,
    projectionEntities: 0,
    checkpoints: 0,
    checkpointBytes: 0,
  };
}
